apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: micronaut-bookman-example
      jib: {}

profiles:
  - name: local
    deploy:
      kubectl:
        manifests: ["k8s/*.yaml", "k8s/local/*.yaml"]

portForward:
  - port: 8080
    localPort: 8080
    resourceType: Service
    namespace: default
    resourceName: bookman
  - port: 3306
    localPort: 9000
    resourceType: Service
    namespace: default
    resourceName: mysql