apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: micronaut-bookman-example
      jib: {}

profiles:
  - name: local
    deploy:
      kubectl:
        manifests: ["k8s/*.yaml", "k8s/local/*.yaml"]