micronaut:
  application:
    name: micronaut-bookman

jackson:
  # ISO 8601
  date-format: "yyyy-MM-dd'T'HH:mm:ssXXX"
  time-zone: "Asia/Tokyo"

datasources:
  default:
      url: jdbc:mysql://${rdb.host}:${rdb.port}/${rdb.database}
      username: ${rdb.user}
      password: ${rdb.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10

flyway:
  datasources:
    default:
      locations: classpath:db/migrations
      enabled: false