apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookman
spec:
  selector:
    matchLabels:
      app: bookman
  template:
    metadata:
      labels:
        app: bookman
    spec:
      containers:
        - name: bookman
          image: micronaut-bookman-example
          ports:
            - containerPort: 8080